Feature/slam toolbox param
KBKN-Autonomous-Robotics-Lab/orange_ros2 pull request #64
Opened 2023-10-03 10:01 UTC by shunki1006

## PR Type

- [x] Feature
- [ ] Bug fix
- [ ] Refactor
- [ ] Documentation
- [ ] Other

## Overview
- slam_toolboxのパラメータ調整(loop_closureのパラメータについては適宜再調整が必要な可能性あり.) 

## Detail
-  Plugin params, ROS Parametersについては変更する必要はなし. 
- 他の部分で主要と思われしものを抜粋. パラメータについて説明したファイルも添付するのでご確認ください.
- map_update_interval；地図の更新頻度のパラメータ. この値を減らすことで地図のリアルタイム性が向上するが計算量が多くなりPCが耐えられなくなるので注意. 
- max_laser_range；レーザースキャンの距離のパラメータ. この値は実機に合わせて設定すると良い. 
- minimum_time_interval；地図の更新頻度のパラメータ. 0.25などに減らしすぎると地図が穴ぼこだらけになるため注意. 
- transform_timeout；システムの待ち時間のパラメータ. 大きい値にするとアップが取れなくなるので注意. 
- minimum_travel_distance(hedding)；新たなスキャンを受け入れるために必要な最小距離(角度)のパラメータ. この値によっってマップ作成中の経路点の間隔が決まる. 大きくするとマップの更新頻度が減少するため粗雑なマップになる. 
- scan_buffer_size；保持するスキャンの数のパラメータ. この値がループクロージャーの検出に役立つ可能性あり. 
[slam_toolbox_param.docx](https://github.com/KBKN-Autonomous-Robotics-Lab/orange_ros2/files/12791268/slam_toolbox_param.docx)

## Test
- [x] つくチャレ確認走行区間での地図作成でテスト済み. 

## Attention
- 機体によってパラメータは変わるため, 鵜呑みにせず自身の機体のパラメータ調整の参考程度にしてください.

2023-10-04 13:30 UTC, Alpaca-zip requested changes
パラメータの調整についてドキュメントを残していただきありがとうございます。
幾つか気になった点があったのでコメントを書いておきました。適宜修正お願い致します。

2023-10-04 13:30 UTC, Alpaca-zip commented on orange_slam/config/offline_slam_toolbox_params.yaml
> +    do_loop_closing: false
これだと、rosbagを利用した地図作成ではループ閉じ込みを使わず、リアルタイムでの地図作成ではループ閉じ込みを使うということになりますが合っていますか？
ループ閉じ込みは処理が重くなるので逆の方が好ましいようにも感じます。

2023-10-05 08:03 UTC, shunki1006 commented
@Alpaca-zip 対応したのでご確認お願いします. 
loop_closureはデフォルトではfalseにして, 使用する必要があるときにtrueにしようと考えています.

2023-10-05 08:23 UTC, Alpaca-zip reviewed
これだと`offline_slam_toolbox_params.yaml`と`online_slam_toolbox_params.yaml`が全く同じになるのでファイルを分ける意味がなくなってしまいますが、実機でもrosbag環境でも地図生成のパフォーマンスは変わりませんか？

2023-10-05 08:23 UTC, Alpaca-zip commented on orange_slam/config/online_slam_toolbox_params.yaml
> +    map_update_interval: 10.0
この数字は変更する必要がありましたか？

2023-10-05 08:23 UTC, Alpaca-zip commented on orange_slam/config/online_slam_toolbox_params.yaml
> +    tf_buffer_duration: 1440.0
こちらも同様です。

2023-10-05 08:28 UTC, shunki1006 commented on orange_slam/config/online_slam_toolbox_params.yaml
> +    map_update_interval: 10.0
ここを上げることで地図の濃さを上げることができるので10.0にあげてしまって問題ないと思います.

2023-10-05 08:28 UTC, shunki1006 commented on orange_slam/config/online_slam_toolbox_params.yaml
> +    tf_buffer_duration: 1440.0
こちらは計算量負荷のことを考えるとあげない方が良いと思うので修正します。

2023-10-05 08:28 UTC, shunki1006 commented
> これだと`offline_slam_toolbox_params.yaml`と`online_slam_toolbox_params.yaml`が全く同じになるのでファイルを分ける意味がなくなってしまいますが、実機でもrosbag環境でも地図生成のパフォーマンスは変わりませんか？

ちなみに, loop_closureを使用しない場合では特段パフォーマンスに違いは見られませんでした。

2023-10-05 08:37 UTC, Alpaca-zip approved these changes

2023-10-05 08:37 UTC, Alpaca-zip commented on orange_slam/config/online_slam_toolbox_params.yaml
> +    map_update_interval: 10.0
ここの値に関しては次回の地図作成時に、問題があれば再検討してください。

2023-10-05 08:37 UTC, merged