Update/with rosbag launch
KBKN-Autonomous-Robotics-Lab/orange_ros2 pull request #96
Opened 2024-10-17 11:44 UTC by shunsugar

## PR Type

- [x] Feature
- [ ] Bug fix
- [ ] Refactor
- [ ] Documentation
- [ ] Other

## Overview
- bagファイルの解析に使うlaunchファイルの更新

## Detail
- bagファイルで生のデータを記録したとき、それらの処理をする実行ファイルをlaunchファイルに記述しました。
- また、launchファイルで実行する順序を入れ替え、現在使っていない部分はコメントアウトしました。

## Test
- [x] I have tested this change with rosbag

## Attention
- Fast lio odomの部分のuse_sim_timeはtrueにすると動かないので、false固定でお願いします。
- また、odom情報の確認はしましたが、点群情報やマップについては確認していません。

2024-10-18 02:59 UTC, shunsugar commented
commit時のコメント間違えてました。
bag -> bug
です。すみません。

2024-10-21 11:43 UTC, kugurofu requested changes
orange_bringup/orange_bringup/lonlat_to_odom.pyの114行目が符号が逆かもしれません。
また、コメントが一部消えているため、修正をお願いしたいです。
orange_bringup/orange_bringup/combination.py  30-31 行目
orange_bringup/orange_bringup/ekf_myself.py  73-74 行目
orange_bringup/orange_bringup/get_lonlat.py  38-39 , 138-140 行目
orange_bringup/orange_bringup/lonlat_to_odom.py  42-43 行目
orange_bringup/orange_bringup/movingbase_yaw_to_quat.py  34-35 , 83 , 172-173 行目

2024-10-21 12:00 UTC, shunsugar commented
修正しましたので、再度確認をお願いします。🙇

2024-10-23 08:19 UTC, kugurofu approved these changes
修正ありがとうございます。マージします。

2024-10-23 08:19 UTC, merged